### ISSUE TITLE
CSV -> Charts

### ISSUE THREAD

**Issue by masoom80** [app-generator/devtool-python-converter#5] opened 2022-12-05 08:24 UTC
Regenerate and datatables are done!
Could you give an example of how the charts should be?

**Comment by app-generator** [comment] 2022-12-05 09:24
Hello guys

the ideal flow is this: 

- user drag & drops  the CVS
- Backend process the information & extract the columns
- the user can select TWO columns (only two) to be  used in charts
- select the chart type: Pie, Line (something simple)
- confirm the action
- get the chart

Being the first iteration and all written from scratch we can have the worst UI/UX but the flow should work. 

Once the flow is stable we can add AJAX & improve the UX .. but this is for the 2nd iteration or the product.

also, let me know if I can help

**Comment by app-generator** [comment] 2022-12-06 10:52
Hello @Mortrest 

The correlation work is not 100% coherent because the chart type is not correlated with the properties x, y values. 
But we can raffinate in 2nd iteration of this. 

The problem is that the generated chart shrinks to a minimum and gets large again. 

The desired layout should be centered with the same width as the drop box. 

Please take a look. Ty! 

![csv-charts-err1-intro](https://user-images.githubusercontent.com/51070104/205891621-b116d286-28ab-41bb-843a-2fa57c17363a.gif)

**Comment by alivarastepour** [comment] 2022-12-06 11:40
please mention steps that produced this problem(the auto shrinking ? I guess). I did not follow.

**Comment by app-generator** [comment] 2022-12-06 12:07
Hello @alivarastepour 

here are the steps. 

- drop the sales_cvs
- select charts
- CHART option:
  - LINE type
  - On-X: purchase date
  - On-Y: price
- Chart is returned -> OK Good
- No, Resize the window (minimization)
  - I had this reflex just to visualize the chart that is somehow positioned below   

Might be a good idea to center the chart area using the same width as the drop zone, 
and move the window focus around generated charts. 

Please take a look. Ty! 

P.S. I will get back on the correlation suggestion (scheduled in Drop2).

**Comment by app-generator** [comment] 2022-12-10 08:23
Validated. Closing. 
Ty guys!

**Closed as completed by app-generator** 2022-12-10 08:23 UTC
Labels: bug
