### ISSUE TITLE
update on the errors

### ISSUE THREAD

**Issue by alivarastepour** [app-generator/devtool-python-converter#38] opened 2023-01-07 12:20 UTC
hi @app-generator 
we need to know if previous issues(#35 #34 #31) are resolved or not. pleases keep us informed.
ty!

**Comment by app-generator** [comment] 2023-01-07 12:51
hello @alivarastepour & guys! 

All mentioned issues are `NOT Fixed`. Please review. Ty!

> Here is the status for each one.

- #35: this cannot be tested in the latest version because the connection is broken in all cases.
  - Issue updated with more context
- #34: the issue is `NOT Fixed`
- #31: the issue is `NOT Fixed`
  - Input expected from the developer: 
![image](https://user-images.githubusercontent.com/51070104/211151461-f9cf7455-a3d7-479f-94d9-31ea8a7bb807.png)

**Comment by app-generator** [comment] 2023-01-18 07:22
Validated. Closing.
Ty!

**Closed as completed by app-generator** 2023-01-18 07:22 UTC
