### ISSUE TITLE
project structure

### ISSUE THREAD

**Issue by alivarastepour** [app-generator/devtool-python-converter#24] opened 2022-12-21 07:37 UTC
hi @app-generator 
working on this project at the first iteration, all functionalities were written in `dnd.js` . however there is a new file `converter.js `which seems to be the source for the same logic now. which file should I modify?

**Comment by app-generator** [comment] 2022-12-21 07:53
Hello @alivarastepour 

Please keep the latest changes & the NEW codebase structure. 

> DND.js/css are renamed. Please initiate your development using the latest version

In case you have questions, I'm here. 

Also, in case you're using Discord, my ID is: 

Sm0ke#7120

Ty

**Comment by app-generator** [comment] 2022-12-23 11:02
Hello guys!

Ty for all the work. Please don't close issues (only QA can do it). 
Once a fix is made, just add a new comment with a mention of `app-generator`. Something like 
`Fix committed. Please check`

Once QA validates the fix, the issue is closed. 
Ty!

**Closed as completed** 2022-12-23 11:19 UTC
Labels: question
